/**
 * Base-14 Helvetica has no encoding declared, so it falls back to
 * StandardEncoding — a single byte per glyph, and one that doesn't contain
 * ₦, ✓, or typographic spaces at all. Left alone, those come out as raw
 * UTF-8 bytes misread as separate Latin-1 glyphs (garbage like "âƒ"). Swap
 * the ones we actually produce and flatten anything else to plain ASCII
 * rather than let it corrupt the page.
 */
function sanitizePdfText(value: string) {
  return value
    .replace(/₦/g, "N") // Naira sign
    .replace(/[‘’]/g, String.fromCharCode(39))
    .replace(/[“”]/g, String.fromCharCode(34))
    .replace(/[–—]/g, "-")
    .replace(/✓/g, "") // checkmark, dropped: the status text already says it
    .replace(/[  -​  　]/g, " ") // unicode spaces
    .replace(/[^ -~]/g, "?");
}
function escapePdfText(value: string) {
  return sanitizePdfText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(value: string, maxChars = 78) {
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length > maxChars) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  if (current) lines.push(current);
  return lines;
}

type PdfLine = {
  text: string;
  size?: number;
  x?: number;
  gapAfter?: number;
  muted?: boolean;
};

export function createSimplePdf(title: string, lines: PdfLine[]) {
  const width = 612;
  const height = 792;
  let y = 688;
  // Light page, purple accent bar and dark ink — the same palette as the
  // in-app ticket (`components/brand/Receipt.tsx`), not a generic dark card.
  const content: string[] = [
    "1 1 1 rg",
    `0 0 ${width} ${height} re f`,
    "0.541 0.310 1 rg",
    "40 712 532 3 re f",
    "0.078 0.071 0.086 rg",
    "BT /F1 28 Tf 40 736 Td (" + escapePdfText(title) + ") Tj ET",
  ];

  for (const line of lines) {
    const size = line.size ?? 11;
    const x = line.x ?? 40;
    const color = line.muted ? "0.44 0.43 0.46 rg" : "0.078 0.071 0.086 rg";
    const wrapped = wrapText(line.text, size > 15 ? 48 : 86);
    for (const row of wrapped) {
      content.push(color);
      content.push(`BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(row)}) Tj ET`);
      y -= Math.max(size + 5, 15);
      if (y < 70) break;
    }
    y -= line.gapAfter ?? 4;
    if (y < 70) break;
  }

  content.push("0.61 0.60 0.64 rg");
  content.push("BT /F1 9 Tf 40 42 Td (Generated by Linq) Tj ET");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content.join("\n"), "utf8")} >>\nstream\n${content.join("\n")}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
