function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(value: string, maxChars = 78) {
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length > maxChars) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  if (current) lines.push(current);
  return lines;
}

type PdfLine = {
  text: string;
  size?: number;
  x?: number;
  gapAfter?: number;
  muted?: boolean;
};

export function createSimplePdf(title: string, lines: PdfLine[]) {
  const width = 612;
  const height = 792;
  let y = 704;
  const content: string[] = [
    "0 0 0 rg",
    `0 0 ${width} ${height} re f`,
    "0.627 0.878 0.671 rg",
    "40 712 532 2 re f",
    "1 1 1 rg",
    "BT /F1 28 Tf 40 736 Td (" + escapePdfText(title) + ") Tj ET",
  ];

  for (const line of lines) {
    const size = line.size ?? 11;
    const x = line.x ?? 40;
    const color = line.muted ? "0.62 0.62 0.62 rg" : "1 1 1 rg";
    const wrapped = wrapText(line.text, size > 15 ? 48 : 86);
    for (const row of wrapped) {
      content.push(color);
      content.push(`BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(row)}) Tj ET`);
      y -= Math.max(size + 5, 15);
      if (y < 70) break;
    }
    y -= line.gapAfter ?? 4;
    if (y < 70) break;
  }

  content.push("0.38 0.38 0.38 rg");
  content.push("BT /F1 9 Tf 40 42 Td (Generated by Linq) Tj ET");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content.join("\n"), "utf8")} >>\nstream\n${content.join("\n")}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
